const express = require('express')
const { home, optionAdmin, UEOption, UEAjout, postUEAjout, UEListe, UEDelete, UEUpdate, postUEUpdate, UESearch, profForm, profPostForm, optionProf, profList, profSupprimer, profUpdateform, profPostUpdate, profRecherche, ecOption, ecChoixSem, ecAjoutForm, ecPostAjout, ecListe, ecRecherche, ecModifier, ecPostModif, ecSupprimer, profMsem, profMattr, postProfMattr, profMoption, ecVoir, ecEnlevProf, edtchoixSem, edtFormAjout, postEdtFormAjout, edtChoixOption, edtSemestreVoir, edtVoir, edtSupprimer, edtPost, edtSupprimerTout, etudiantOption, etudiantAjoutChoixSem, etudiantFormAjout, etudiantPostAjout, etudiantListe, etudiantRech, etudiantVoir, etudiantFormMaj, etudiantPostMaj, etudiantSuppr, etudiantChoiSemDel, etudiantChoixDel, etudiantNominDel, etudiantEnlevStat, etudiantRechDel, voirDelegue, profVoir, profVoirEtat, CDTchoixSem, CDTlisteEC, CDTvoir, CDTreset, importExcel, loginForm, auth, profValideFinance, deconnexion, UEchoixSem, UEverifSem, UEvalidationOp, ecChoixOption, etudiantChoixOp, etudiantChoixOpDel, profMattrChoixOp, edtOpFiliere, edtChoixOp, ajoutFiliere, postAjoutFiliere, CDTchoixOp, etudiantListeParNiv, etudiantRechParSem } = require('../controllers/AdminController')
const { noteChoixSem, noteEtudiant, noteFormAjout, notePost, etudiantNoteRech, listeEtudRep, noteVoir, noteRepech, notePostRepech, noteChoixOp } = require('../controllers/AdminNoteController')
const {ensureAuthenticated , passUserAdmin , passUserFinance, passAdminAndFinance} = require('../config/security')
const router = express.Router()


router.get('/home' ,ensureAuthenticated ,passUserAdmin, home)
router.get('/optionAdmin/:FiliereId' ,ensureAuthenticated ,passUserAdmin, optionAdmin)
router.get('/optionAdmin/UE/:FiliereId' ,ensureAuthenticated ,passUserAdmin, UEOption)
router.get('/optionAdmin/UE/ajouter/:FiliereId' ,ensureAuthenticated ,passUserAdmin, UEAjout)
router.get('/optionAdmin/UE/liste/:FiliereId' ,ensureAuthenticated ,passUserAdmin, UEListe)
router.get('/optionAdmin/UE/delete/:FiliereId/:SemestreId/:UEId/:OptionId' ,ensureAuthenticated ,passUserAdmin, UEDelete)
router.get('/optionAdmin/UE/update/:FiliereId/:SemestreId/:UEId/:OptionId' ,ensureAuthenticated ,passUserAdmin, UEUpdate)
router.get('/optionAdmin/UE/choixSem/:FiliereId' , ensureAuthenticated , passUserAdmin, UEchoixSem)
router.get('/optionAdmin/UE/verifSemestre/:FiliereId/:SemestreId' , ensureAuthenticated , passUserAdmin, UEverifSem)
router.get('/optionAdmin/UE/validation_option/:FiliereId/:SemestreId/:OptionId' , UEvalidationOp)
router.get('/ajout_filiere' , ensureAuthenticated , passUserAdmin , ajoutFiliere )
router.get('/professeur/formAjout' ,ensureAuthenticated ,passUserAdmin, profForm)
router.get('/professeur/voir/:id' ,ensureAuthenticated,passAdminAndFinance , profVoir)
router.get('/professeur/liste' ,ensureAuthenticated ,passAdminAndFinance, profList)
router.get('/professeur/voir_etat/:matricule' ,ensureAuthenticated ,passUserFinance, profVoirEtat)
router.get('/professeur/supprimer/:id' ,ensureAuthenticated ,passUserAdmin, profSupprimer)
router.get('/professeur/modifier/:id' ,ensureAuthenticated ,passUserAdmin, profUpdateform)
router.get('/professeur/enlever/:ECId/:FiliereId/:SemestreId/:UtilisateurId' ,ensureAuthenticated ,passUserAdmin, ecEnlevProf)
router.get('/professeur/importer/:matricule' , ensureAuthenticated,passUserFinance,importExcel)
router.get('/professeur/Validation/:matricule' , ensureAuthenticated, passUserFinance, profValideFinance)
router.get('/optionProf' ,ensureAuthenticated ,passUserAdmin, optionProf)
router.get('/ec/option/:FiliereId' ,ensureAuthenticated ,passUserAdmin, ecOption)
router.get('/ec/semestre/:FiliereId' ,ensureAuthenticated ,passUserAdmin, ecChoixSem)
router.get('/ec/ajout/:FiliereId/:SemestreId' ,ensureAuthenticated ,passUserAdmin, ecAjoutForm)
router.get('/ec/liste/:FiliereId' ,ensureAuthenticated ,passUserAdmin, ecListe)
router.get('/ec/modifier/:ECId/:SemestreId/:FiliereId' ,ensureAuthenticated ,passUserAdmin, ecModifier)
router.get('/ec/voir/:ECId/:SemestreId/:FiliereId' ,ensureAuthenticated ,passUserAdmin, ecVoir)
router.get('/ec/ajout/choixOption/:FiliereId/:SemestreId/:OptionId' , ecChoixOption)
router.get('/edt/gerer/choixSemestre/:FiliereId' ,ensureAuthenticated ,passUserAdmin, edtchoixSem)
router.get('/edt/choixFiliere_option/:FiliereId/:SemestreId/:OptionId' ,ensureAuthenticated ,passUserAdmin, edtOpFiliere)
router.get('/edt/ajout/:FiliereId/:SemestreId',ensureAuthenticated ,passUserAdmin,edtFormAjout)
router.get('/edt/choixOption/:FiliereId',ensureAuthenticated ,passUserAdmin,edtChoixOption)
router.get('/edt/voirChoix/choixSemestre/:FiliereId', ensureAuthenticated , passUserAdmin , edtSemestreVoir)
router.get('/edt/voir/:FiliereId/:SemestreId',ensureAuthenticated ,passUserAdmin,edtVoir)
router.get('/edt/voir/choix_option/:FiliereId/:SemestreId/:OptionId' ,ensureAuthenticated ,passUserAdmin, edtChoixOp)
router.get('/edt/supprimer/:FiliereId/:SemestreId/:JourId/:ECId/:OptionId' ,ensureAuthenticated ,passUserAdmin, edtSupprimer)
router.get('/edt/supprimerEdt/:FiliereId/:SemestreId/:OptionId',ensureAuthenticated ,passUserAdmin, edtSupprimerTout)
router.get('/ec/supprimer/:ECId/:FiliereId' ,ensureAuthenticated ,passUserAdmin, ecSupprimer)
router.get('/prof&mat/choixSem/:FiliereId' ,ensureAuthenticated ,passUserAdmin, profMsem)
router.get('/prof&mat/choix_option/:FiliereId/:SemestreId/:OptionId' ,ensureAuthenticated ,passUserAdmin, profMattrChoixOp)
router.get('/prof&mat/attribuer/:FiliereId/:SemestreId' ,ensureAuthenticated ,passUserAdmin, profMattr)
router.get('/etudiant/:FiliereId' , ensureAuthenticated ,passUserAdmin,etudiantOption)
router.get('/etudiant/ajout/choixSem/:FiliereId' , ensureAuthenticated ,passUserAdmin,etudiantAjoutChoixSem)
router.get('/etudiant/ajout/:FiliereId/:SemestreId' ,ensureAuthenticated ,passUserAdmin, etudiantFormAjout)
router.get('/etudiant/liste/:FiliereId' ,ensureAuthenticated ,passUserAdmin, etudiantListe)
router.get('/etudiant/voir/:FiliereId/:UtilisateurId' ,ensureAuthenticated ,passUserAdmin, etudiantVoir)
router.get('/etudiant/modifier/:FiliereId/:UtilisateurId/:SemestreId' ,ensureAuthenticated ,passUserAdmin, etudiantFormMaj)
router.get('/etudiant/supprimer/:FiliereId/:UtilisateurId/:SemestreId' ,ensureAuthenticated ,passUserAdmin, etudiantSuppr)
router.get('/etudiant/nominationDeleg/choixSem/:FiliereId' ,ensureAuthenticated ,passUserAdmin, etudiantChoiSemDel)
router.get('/etudiant/choixSemDel/:FiliereId/:SemestreId' ,ensureAuthenticated ,passUserAdmin, etudiantChoixDel)
router.get('/delegue/choix_option/:FiliereId/:SemestreId/:OptionId' ,ensureAuthenticated ,passUserAdmin, etudiantChoixOpDel)
router.get('/etudiant/nommer/delegue/:FiliereId/:SemestreId/:UtilisateurId/:OptionId' ,ensureAuthenticated ,passUserAdmin, etudiantNominDel)
router.get('/etudiant/enlever/statut/:FiliereId/:SemestreId/:UtilisateurId/:OptionId' ,ensureAuthenticated ,passUserAdmin, etudiantEnlevStat)
router.get('/etudiant/liste/delegue/:FiliereId' ,ensureAuthenticated ,passUserAdmin, voirDelegue)
router.get('/etudiant/liste_par_niv/:FiliereId/:SemestreId' ,ensureAuthenticated ,passUserAdmin, etudiantListeParNiv)
router.get('/etudiant/choix_option/:FiliereId/:SemestreId/:OptionId' ,ensureAuthenticated ,passUserAdmin, etudiantChoixOp)
router.get('/note/choixSem/:FiliereId' ,ensureAuthenticated ,passUserAdmin, noteChoixSem)
router.get('/note/etudiant/:FiliereId/:SemestreId' ,ensureAuthenticated ,passUserAdmin, noteEtudiant)
router.get('/note/ajout/:FiliereId/:SemestreId/:UtilisateurId/:OptionId' ,ensureAuthenticated ,passUserAdmin, noteFormAjout)
router.get('/note/option_etudiant/:FiliereId/:SemestreId/:OptionId' ,ensureAuthenticated , passUserAdmin , noteChoixOp)
router.get('/note/voir/:FiliereId/:UtilisateurId/:SemestreId/:OptionId' ,ensureAuthenticated ,passUserAdmin, noteVoir)
router.get('/note/Noterepech/:FiliereId/:UtilisateurId/:SemestreId/:OptionId' ,ensureAuthenticated ,passUserAdmin, noteRepech)
router.get('/CDT/semestre/:FiliereId' ,ensureAuthenticated ,passUserAdmin, CDTchoixSem)
router.get('/CDT/liste_EC/:FiliereId/:SemestreId' ,ensureAuthenticated ,passUserAdmin, CDTlisteEC)
router.get('/CDT/voir/:FiliereId/:SemestreId/:ECId' ,ensureAuthenticated ,passUserAdmin, CDTvoir)
router.get('/CDT/resetAll_CDT/:FiliereId/:SemestreId' ,ensureAuthenticated ,passUserAdmin, CDTreset)
router.get('/CDT/choix_option/liste_EC/:FiliereId/:SemestreId/:OptionId' ,ensureAuthenticated ,passUserAdmin, CDTchoixOp)
router.get('/finance/deconnexion' ,ensureAuthenticated,passUserFinance,deconnexion)
router.get('/deconnexion' ,ensureAuthenticated,passUserAdmin,deconnexion)
router.get('/login' ,loginForm)
router.post('/login' , auth)
router.post('/ajout_filiere' , ensureAuthenticated , passUserAdmin , postAjoutFiliere )
router.post('/etudiant/choixSemDel/:FiliereId/:SemestreId' , ensureAuthenticated ,passUserAdmin,etudiantRechDel)
router.post('/delegue/choix_option/:FiliereId/:SemestreId/:OptionId' ,ensureAuthenticated ,passUserAdmin, etudiantRechDel)
router.post('/note/Noterepech/:FiliereId/:UtilisateurId/:SemestreId/:OptionId' ,ensureAuthenticated ,passUserAdmin, notePostRepech)
router.post('/note/etudiant/:FiliereId/:SemestreId' ,ensureAuthenticated ,passUserAdmin, etudiantNoteRech)
router.post('/note/option_etudiant/:FiliereId/:SemestreId/:OptionId' ,ensureAuthenticated ,passUserAdmin, etudiantNoteRech)
router.post('/note/ajout/:FiliereId/:SemestreId/:UtilisateurId/:OptionId' ,ensureAuthenticated ,passUserAdmin, notePost)
router.post('/note/ajout/:FiliereId/:SemestreId/:UtilisateurId/:OptionId' ,ensureAuthenticated ,passUserAdmin, noteFormAjout)
router.post('/etudiant/modifier/:FiliereId/:UtilisateurId/:SemestreId' ,ensureAuthenticated ,passUserAdmin, etudiantPostMaj)
router.post('/etudiant/liste/:FiliereId' ,ensureAuthenticated ,passUserAdmin, etudiantRech)
router.post('/etudiant/ajout/:FiliereId/:SemestreId' ,ensureAuthenticated ,passUserAdmin, etudiantPostAjout)
router.post('/etudiant/choix_option/:FiliereId/:SemestreId/:OptionId' ,ensureAuthenticated ,passUserAdmin, etudiantPostAjout)
router.post('/edt/voir/:FiliereId/:SemestreId',ensureAuthenticated ,passUserAdmin, edtPost)
router.post('/edt/voir/choix_option/:FiliereId/:SemestreId/:OptionId' ,ensureAuthenticated ,passUserAdmin, edtPost)
router.post('/edt/ajout/:FiliereId/:SemestreId',ensureAuthenticated ,passUserAdmin,postEdtFormAjout)
router.post('/edt/choixFiliere_option/:FiliereId/:SemestreId/:OptionId',ensureAuthenticated ,passUserAdmin,postEdtFormAjout)
router.post('/prof&mat/attribuer/:FiliereId/:SemestreId' ,ensureAuthenticated ,passUserAdmin, postProfMattr)
router.post('/prof&mat/choix_option/:FiliereId/:SemestreId/:OptionId' ,ensureAuthenticated ,passUserAdmin, postProfMattr)
router.post('/ec/liste/:FiliereId' ,ensureAuthenticated ,passUserAdmin, ecRecherche)
router.post('/ec/ajout/:FiliereId/:SemestreId' ,ensureAuthenticated ,passUserAdmin, ecPostAjout)
router.post('/ec/ajout/choixOption/:FiliereId/:SemestreId/:OptionId',ensureAuthenticated ,passUserAdmin, ecPostAjout)
router.post('/professeur/liste' ,ensureAuthenticated ,passAdminAndFinance, profRecherche)
router.post('/professeur/modifier/:id' ,ensureAuthenticated ,passUserAdmin, profPostUpdate)
router.post('/professeur/formAjout' ,ensureAuthenticated ,passUserAdmin, profPostForm)
router.post('/optionAdmin/UE/update/:FiliereId/:SemestreId/:UEId/:OptionId' ,ensureAuthenticated ,passUserAdmin, postUEUpdate)
router.post('/etudiant/liste_par_niv/:FiliereId/:SemestreId' ,ensureAuthenticated ,passUserAdmin, etudiantRechParSem)
router.post('/optionAdmin/UE/verifSemestre/:FiliereId/:SemestreId' ,ensureAuthenticated ,passUserAdmin, postUEAjout)
router.post('/optionAdmin/UE/validation_option/:FiliereId/:SemestreId/:OptionId' ,ensureAuthenticated ,passUserAdmin,postUEAjout )
router.post('/optionAdmin/UE/liste/:FiliereId' ,ensureAuthenticated ,passUserAdmin, UESearch)
router.post('/ec/modifier/:ECId/:SemestreId/:FiliereId' ,ensureAuthenticated ,passUserAdmin, ecPostModif)


module.exports = router

